# Generated by Django 4.2.5 on 2023-09-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_name_job_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='Job',
        ),
    ]
